apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-microservice
spec:
  selector:
    matchLabels:
      app: library-microservice
  template:
    metadata:
      labels:
        app: library-microservice
    spec:
      containers:
        - name: book-catalog
          image: librarymicroservice.azurecr.io/book-catalog:latest
          ports:
            - containerPort: 8001
          env:
            - name: DATABASE_URL
              value: postgresql://library_microservice_user:4MpXWkRgkGfUqfFV6AG8Z91w21ChyfYT@dpg-crmnf323esus7380ebcg-a.oregon-postgres.render.com/library_microservice
        - name: inventory-management
          image: librarymicroservice.azurecr.io/inventory-management:latest
          ports:
            - containerPort: 8002
          env:
            - name: DATABASE_URL
              value: postgresql://library_microservice_user:4MpXWkRgkGfUqfFV6AG8Z91w21ChyfYT@dpg-crmnf323esus7380ebcg-a.oregon-postgres.render.com/library_microservice
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  selector:
    app: library-microservice
  ports:
    - port: 8001
      targetPort: 8001
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management-service
spec:
  selector:
    app: library-microservice
  ports:
    - port: 8002
      targetPort: 8002
  type: LoadBalancer
